In [14]:
import xgboost as xgb
import numpy as np
import pandas as pd
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import GridSearchCV, KFold, cross_val_score 
from sklearn.metrics import make_scorer, mean_squared_error

In [15]:
TrainData = pd.read_csv('C:/Users/14702/Downloads/TrainDataForBCExample.csv',sep=',',header=0,quotechar='"')
ValData = pd.read_csv('C:/Users/14702/Downloads/ValDataForBCExample.csv',sep=',',header=0,quotechar='"')

# drop the column not needed 
# TrainData.drop(0,axis = 1) 
# Val_Data = ValData.drop([0,2],axis = 1)

Vars = list(TrainData)
# YTr = np.array(TrainData[[1]])
YTr = np.array(TrainData[Vars[0]])
XTr = np.array(TrainData.loc[:,Vars[1:]])

Vars = list(ValData)
YVal = np.array(ValData[Vars[0]])
XVal = np.array(ValData.loc[:,Vars[1:]])

XTr.shape
XVal.shape

print(YVal)
print(YTr)
min(YTr)
# Rescale Training Data

XTrRsc = (XTr - XTr.min(axis=0))/XTr.ptp(axis=0)
XTrRsc.shape
XTrRsc.min(axis=0)
XTrRsc.max(axis=0)

# Note YTr does not need to be rescaled since it is binary

#Rescale Validation Data. Really should use Training parameters to rescale.
XValRsc = (XVal - XTr.min(axis=0))/XTr.ptp(axis=0)
XValRsc.shape
XValRsc.min(axis=0)
XValRsc.max(axis=0)

[1 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [38]:
# Retrieving Attributes
X = TrainData.values[:,2:]
y = TrainData.values[:,1]

X=X.astype('float64')
y=y.astype('int')

In [16]:
dtrain = xgb.DMatrix(data=XTr,label=YTr)
dval = xgb.DMatrix(data=XVal,label=YVal)

param = { 'objective': 'binary:logistic', 'max_depth':5,'min_child_weight':5}
# 'max_depth': 2, 'eta': 1,

num_round = 5000
evallist = [(dval, 'eval'), (dtrain, 'train')]
bst = xgb.train(param, dtrain, num_round, evallist,early_stopping_rounds=100)

[0]	eval-error:0.168662	train-error:0.168138
Multiple eval metrics have been passed: 'train-error' will be used for early stopping.

Will train until train-error hasn't improved in 100 rounds.
[1]	eval-error:0.168662	train-error:0.168138
[2]	eval-error:0.168125	train-error:0.167624
[3]	eval-error:0.168125	train-error:0.167624
[4]	eval-error:0.168094	train-error:0.167607
[5]	eval-error:0.167912	train-error:0.167472
[6]	eval-error:0.167909	train-error:0.167468
[7]	eval-error:0.167925	train-error:0.167547
[8]	eval-error:0.167948	train-error:0.167476
[9]	eval-error:0.168024	train-error:0.167648
[10]	eval-error:0.167895	train-error:0.167482
[11]	eval-error:0.167991	train-error:0.167594
[12]	eval-error:0.167927	train-error:0.167553
[13]	eval-error:0.167929	train-error:0.167562
[14]	eval-error:0.167958	train-error:0.16757
[15]	eval-error:0.168042	train-error:0.167601
[16]	eval-error:0.168081	train-error:0.167614
[17]	eval-error:0.168055	train-error:0.1676
[18]	eval-error:0.16807	train-error:0

[175]	eval-error:0.166766	train-error:0.166047
[176]	eval-error:0.166772	train-error:0.166051
[177]	eval-error:0.166751	train-error:0.166028
[178]	eval-error:0.166705	train-error:0.166025
[179]	eval-error:0.166718	train-error:0.166036
[180]	eval-error:0.1667	train-error:0.16603
[181]	eval-error:0.166705	train-error:0.166031
[182]	eval-error:0.1667	train-error:0.166031
[183]	eval-error:0.166702	train-error:0.166033
[184]	eval-error:0.166678	train-error:0.166012
[185]	eval-error:0.166678	train-error:0.166011
[186]	eval-error:0.16669	train-error:0.166015
[187]	eval-error:0.166675	train-error:0.165987
[188]	eval-error:0.166662	train-error:0.165983
[189]	eval-error:0.166666	train-error:0.165982
[190]	eval-error:0.166668	train-error:0.165988
[191]	eval-error:0.166662	train-error:0.165986
[192]	eval-error:0.166658	train-error:0.165981
[193]	eval-error:0.166662	train-error:0.165985
[194]	eval-error:0.166649	train-error:0.165971
[195]	eval-error:0.166644	train-error:0.16597
[196]	eval-error:0.1

[351]	eval-error:0.166355	train-error:0.165681
[352]	eval-error:0.166358	train-error:0.165679
[353]	eval-error:0.166346	train-error:0.165675
[354]	eval-error:0.166363	train-error:0.165685
[355]	eval-error:0.166365	train-error:0.165682
[356]	eval-error:0.166352	train-error:0.165678
[357]	eval-error:0.16635	train-error:0.165678
[358]	eval-error:0.166327	train-error:0.165684
[359]	eval-error:0.166346	train-error:0.165677
[360]	eval-error:0.166344	train-error:0.165673
[361]	eval-error:0.166333	train-error:0.165669
[362]	eval-error:0.166336	train-error:0.165667
[363]	eval-error:0.166336	train-error:0.165667
[364]	eval-error:0.166333	train-error:0.165674
[365]	eval-error:0.166328	train-error:0.16568
[366]	eval-error:0.166323	train-error:0.165674
[367]	eval-error:0.16632	train-error:0.165675
[368]	eval-error:0.166321	train-error:0.165671
[369]	eval-error:0.166319	train-error:0.165672
[370]	eval-error:0.166318	train-error:0.165669
[371]	eval-error:0.166316	train-error:0.165669
[372]	eval-error

[527]	eval-error:0.16633	train-error:0.165537
[528]	eval-error:0.166324	train-error:0.165538
[529]	eval-error:0.166326	train-error:0.165537
[530]	eval-error:0.166326	train-error:0.165536
[531]	eval-error:0.166321	train-error:0.165532
[532]	eval-error:0.166327	train-error:0.165531
[533]	eval-error:0.166327	train-error:0.165531
[534]	eval-error:0.166325	train-error:0.16553
[535]	eval-error:0.166327	train-error:0.16553
[536]	eval-error:0.166327	train-error:0.165529
[537]	eval-error:0.166326	train-error:0.165525
[538]	eval-error:0.16632	train-error:0.165525
[539]	eval-error:0.166321	train-error:0.165526
[540]	eval-error:0.166318	train-error:0.165521
[541]	eval-error:0.166303	train-error:0.165516
[542]	eval-error:0.166309	train-error:0.165521
[543]	eval-error:0.166311	train-error:0.165522
[544]	eval-error:0.166322	train-error:0.165529
[545]	eval-error:0.16632	train-error:0.165531
[546]	eval-error:0.166314	train-error:0.165531
[547]	eval-error:0.166311	train-error:0.165531
[548]	eval-error:0

KeyboardInterrupt: 

In [13]:
ypred = bst.predict(dval, ntree_limit=bst.best_ntree_limit)

def ll(YVal,ypred):
    ll = -np.mean(YVal*np.log(ypred)+(1-YVal)*np.log(1-ypred))
    return(ll)

ll(YVal,ypred)

0.40306710180890254

In [22]:
def lln(YVal,ypred):
    ll = np.mean(YVal*np.log(ypred)+(1-YVal)*np.log(1-ypred))
    return(ll)

In [17]:
X = -np.mean(YVal*np.log(ypred)+(1-YVal)*np.log(1-ypred))

In [20]:
ll(YVal,ypred)

0.40364083283462887

In [5]:
new_scorer=make_scorer(ll, greater_is_better=False)

param_test2 = {
 'max_depth':[2,3,4,5,6,7,8,9,10,None],
 'min_child_weight':[2,3,4,5,6,7,8,9,10,None],
 'learning_rate':[i/100.0 for i in range(0,30)],
 'gamma':[i/100.0 for i in range(0,30)],
 'subsample':[i/10.0 for i in range(6,10)],
 'colsample_bytree':[i/10.0 for i in range(6,10)],
 'reg_alpha':[1e-5, 1e-2, 0.1, 1, 100]
}
gsearch2 = GridSearchCV(
    estimator = XGBClassifier(objective= 'binary:logistic',scale_pos_weight=1,seed=27), 
    param_grid = param_test2, 
    scoring=new_scorer,
    n_jobs=-1, cv=5)
gsearch2.fit(XTr,YTr)
gsearch2.grid_scores_ 
gsearch2.best_params_     
gsearch2.best_score_


exception calling callback for <Future at 0x21111e6bc18 state=finished raised TerminatedWorkerError>
Traceback (most recent call last):
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 309, in __call__
    self.parallel.dispatch_next()
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 731, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\14702\Anaconda3\lib\site-packages\sklearn\externals\jo

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

In [6]:
############################## XGboost Parameter Tuning ##############################
new_scorer=make_scorer(ll, greater_is_better=False)

param_test2 = {
 'max_depth':[1,2,3,4,5,6,7,8,9,10,None],
 'min_child_weight':[1,2,3,4,5,6,7,8,9,10,None]
}
gsearch2 = GridSearchCV(
    estimator = XGBClassifier(objective= 'binary:logistic',scale_pos_weight=1,seed=27), 
    param_grid = param_test2, 
    scoring=new_scorer,
    cv=5)
gsearch2.fit(XTr,YTr)
gsearch2.grid_scores_ 
gsearch2.best_params_     
gsearch2.best_score_

C:\Users\14702\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
C:\Users\14702\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  


KeyboardInterrupt: 

In [28]:
############################## XGboost Parameter Tuning ##############################
num_round = 200

# warnings.filterwarnings('ignore')

gs_dt2 = GridSearchCV(xgb.train(dtrain,evallist,num_round,early_stopping_rounds=5),
                  param_grid=[{'max_depth':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,None],
                               'min_child_weight':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,None], 
                               'subsample':[0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85,0.9,0.95],
                               'gamma':[i/100.0 for i in range(0,30)]}],
                  scoring= lln(YVal,bst.predict(dval)),
                  n_jobs=-1)

gs_dt2 = gs_dt2.fit()

print("Non-nested CV F1-score: ", gs_dt2.best_score_)
print("Optimal Parameter: ", gs_dt2.best_params_)
print("Optimal Estimator: ", gs_dt2.best_estimator_)



TypeError: invalid cache item: list

In [ ]:
nested_score_gs_dt2 = cross_val_score(gs_dt2, X=X, y=y, cv=outer_cv)
print("Nested CV F1-score: ",nested_score_gs_dt2.mean(), " +/- ", nested_score_gs_dt2.std())